use game::map::{MAP_HEIGHT, MAP_WIDTH};

pub const TILE_SIZE: f32 = 4.0;
pub const MAP_PIXEL_WIDTH: f32 = MAP_WIDTH as f32 * TILE_SIZE;
pub const MAP_PIXEL_HEIGHT: f32 = MAP_HEIGHT as f32 * TILE_SIZE;
pub const PLAYER_SIZE: f32 = TILE_SIZE * 0.7;
pub const VISIBLE_CELLS: f32 = 7.0;
pub const VISIBLE_SIZE: f32 = VISIBLE_CELLS * TILE_SIZE;
pub const WINDOW_SCALE: f32 = 16.0;
pub const WINDOW_SIZE: f32 = VISIBLE_SIZE * WINDOW_SCALE;
